<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mass Intentions Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            color: #333;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
            color: #1a56db;
        }
        .header h2 {
            margin: 5px 0;
            font-size: 16px;
            color: #666;
        }
        .header p {
            margin: 3px 0;
            font-size: 11px;
            color: #666;
        }
        .info-section {
            margin-bottom: 15px;
            display: flex;
            justify-content: space-between;
        }
        .info-item {
            font-size: 11px;
        }
        .info-item strong {
            color: #1a56db;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background-color: #1a56db;
            color: white;
            padding: 8px 5px;
            text-align: left;
            font-size: 9px;
            font-weight: bold;
            border: 1px solid #ddd;
        }
        td {
            padding: 6px 5px;
            border: 1px solid #ddd;
            font-size: 8px;
            vertical-align: top;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .applicant-cell {
            font-weight: bold;
            color: #1a56db;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 9px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .no-data {
            text-align: center;
            padding: 30px;
            color: #999;
            font-size: 12px;
        }
        .summary {
            margin-top: 15px;
            padding: 10px;
            background-color: #f0f9ff;
            border: 1px solid #1a56db;
            border-radius: 4px;
        }
        .summary strong {
            color: #1a56db;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $church->ChurchName ?? 'Church' }}</h1>
        <h2>Mass Intentions Report</h2>
        <p><strong>Service:</strong> {{ $service->ServiceName }}</p>
        <p><strong>Date:</strong> {{ \Carbon\Carbon::parse($date)->format('l, F j, Y') }}</p>
        @if(isset($scheduleTime) && $scheduleTime->StartTime && $scheduleTime->EndTime)
        <p><strong>Time:</strong> {{ \Carbon\Carbon::parse($scheduleTime->StartTime)->format('g:i A') }} - {{ \Carbon\Carbon::parse($scheduleTime->EndTime)->format('g:i A') }}</p>
        @endif
        <p><strong>Generated:</strong> {{ \Carbon\Carbon::now()->format('F j, Y - h:i A') }}</p>
    </div>

    @if(count($reportData) > 0)
        <div class="summary">
            <strong>Total Approved Appointments:</strong> {{ count($reportData) }}
        </div>

        <table>
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    @foreach($formElements as $element)
                        <th style="width: {{ 95 / count($formElements) }}%;">{{ $element->Label }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($reportData as $index => $data)
                    <tr>
                        <td style="text-align: center;">{{ $index + 1 }}</td>
                        @foreach($data['form_data'] as $formItem)
                            <td>{{ $formItem['answer'] }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <p>No approved appointments found for this date.</p>
        </div>
    @endif

    <div class="footer">
        <p>This report was automatically generated by the Church Management System</p>
        <p>© {{ \Carbon\Carbon::now()->format('Y') }} {{ $church->ChurchName ?? 'Church' }}. All rights reserved.</p>
    </div>
</body>
</html>
